### ISSUE TITLE
Loading some vacabularies fails

### ISSUE THREAD

**Issue by mkllnk** [datafoodconsortium/connector-ruby#3]
I downloaded the latest files from http://static.datafoodconsortium.org/data/facets.json but could load only two of three vocabulary files.

- `loadMeasures` raises:
  ```
   NameError: `@4PACK' is not allowed as an instance variable name
   from .../gems/datafoodconsortium-connector-1.0.0.pre.alpha.1/lib/datafoodconsortium/connector/skos_parser.rb:29:in `instance_variable_set'
  ```
- `loadFacets` works.
- `loadProductTypes` raises:
   ```
   NoMethodError: undefined method `hasAttribute' for nil:NilClass
   from .../gems/datafoodconsortium-connector-1.0.0.pre.alpha.1/lib/datafoodconsortium/connector/skos_parser.rb:116:in `setResults'
   ```

**Comment by lecoqlibre** [comment]
I just released the [1.0.0.pre.alpha.2](https://rubygems.org/gems/datafoodconsortium-connector/versions/1.0.0.pre.alpha.2) version that should have fix the problem.

The DFC SKOS vocabularies contain elements that start with a number. The connector was trying to use these names but a Ruby variable can't start with a number. Right now I added a fix to have these names starting with an "_" instead of a number. Instead of `connector.MEASURES.QUANTITY.QUANTITYUNIT.4PACK` you will have to use `connector.MEASURES.QUANTITY.QUANTITYUNIT._4PACK`.

I asked the DFC team if we can replace these names directly in the SKOS files. This would be more convenient. See https://github.com/datafoodconsortium/ontology/issues/66.

Can you confirm @mkllnk?

**Comment by mkllnk** [comment]
I can now load measures. :heavy_check_mark: 

But loading product types still fails:

```
NoMethodError: undefined method `hasAttribute' for nil:NilClass
from /.../gems/datafoodconsortium-connector-1.0.0.pre.alpha.2/lib/datafoodconsortium/connector/skos_parser.rb:125:in `setResults'
```

**Comment by lecoqlibre** [comment]
OK it should be fixed now with the [v1.0.0.pre.alpha.3](https://rubygems.org/gems/datafoodconsortium-connector/versions/1.0.0.pre.alpha.3).

Do you confirm @mkllnk?

**Comment by mkllnk** [comment]
Yes, I can load vocabularies now.
